version: '3.8'
services:
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: cases123
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_DATABASE: case_studies
    ports:
      - "3306:3306"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: cases123
      DB_NAME: case_studies